device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.EqualErrorRate
    device: ${metrics.device}
    name: "EqualErrorRate"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.EqualErrorRate
    device: ${metrics.device}
    name: "EqualErrorRate"
