defaults:
  - model: lcnn
  - metrics: eer
  - datasets: asvspoof2019_la_eval # we do not want to run inference on training data
  - dataloader: main
  - transforms: main
  - _self_
inferencer:
  device_tensors: ["image", "labels"] # which tensors should be on device (ex. GPU)
  device: auto # device name or "auto"
  save_path: "asvspoof2019_la_eval" # any name here, can be a dataset name
  seed: 1
  from_pretrained: "saved/model_best.pth" # path to the pretrained model
