train:
  spectrogram: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.Compose
    transforms:
    - _target_: src.transforms.AugsCreation
    - _target_: torchaudio.transforms.MelSpectrogram
      sample_rate: 16000
      n_fft: 512
      win_length: 320
      hop_length: 160
      n_mels: 20
    - _target_: src.transforms.AbsLog
    - _target_: src.transforms.PadOrTrunc
inference:
  spectrogram: # name of the tensor on which we apply transform
    _target_: torchvision.transforms.Compose
    transforms:
    - _target_: torchaudio.transforms.MelSpectrogram
      sample_rate: 16000
      n_fft: 512
      win_length: 320
      hop_length: 160
      n_mels: 20
    - _target_: src.transforms.AbsLog
    - _target_: src.transforms.PadOrTrunc
